### ISSUE TITLE
Camera Calibration Parameters

### ISSUE THREAD

**Issue by rahulsngh883** [skhadem/3D-BoundingBox#2]
Hi ... I am currently working on my data generated using Unity. I am not able to get proper 3D bounding box. My 2D bounding box output is proper but 3D box is going for a toss. I am working on data's generated using Unity 3D. My Image size is 1024 x 1024. What are the changes i need to do in order to map the 3D box on my data.

**Comment by skhadem** [comment]
You are using unity for generating the scene? If so, my guess would be the camera calibration matrix. Does unity provide a way to obtain that information?

**Comment by skhadem** [comment]
Closing unless you can get some more on Unity Camera cal
