### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lxy-mini** [skhadem/3D-BoundingBox#28]
yolo
Using previous model epoch_90.pkl
/home/zjut/anaconda3/envs/pytorch_GPU/lib/python3.7/site-packages/torchvision/models/_utils.py:209: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  f"The parameter '{pretrained_param}' is deprecated since 0.13 and will be removed in 0.15, "
/home/zjut/anaconda3/envs/pytorch_GPU/lib/python3.7/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=VGG19_BN_Weights.IMAGENET1K_V1`. You can also use `weights=VGG19_BN_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "Run.py", line 203, in <module>
    main()
  File "Run.py", line 137, in main
    detections = yolo.detect(yolo_img)
  File "/home/zjut/code/3D-BoundingBox/yolo/yolo.py", line 31, in detect
    (H,W) = image.shape[:2]
ValueError: not enough values to unpack (expected 2, got 0)

**Comment by jamesheatonrdm** [comment]
Looks like an error in your image file, it appears as if your image is None. I do not know what that image file is, so cannot help you without more information.

**Comment by niuDavid** [comment]
The problem that i have met .The reason is that the verison of torchvision is too high .Use the lower version ,such as 0.12, you question may be solved.

**Comment by lxy-mini** [comment]
> 看起来你的图像文件中有错误，看起来好像你的图像是无。我不知道那个图像文件是什么，所以没有更多信息无法帮助你。

yes,you are right! i change my path,and be ok

**Comment by upper127** [comment]
how to do
